[package]
name = "flutter-issue-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.136"
wasm-bindgen = "0.2.80"
wasm-logger = "0.2.0"
yew = "0.19.3"
